// Generated by gencpp from file robint_msgs/AutoRelocationRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_AUTORELOCATIONREQUEST_H
#define ROBINT_MSGS_MESSAGE_AUTORELOCATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace robint_msgs
{
template <class ContainerAllocator>
struct AutoRelocationRequest_
{
  typedef AutoRelocationRequest_<ContainerAllocator> Type;

  AutoRelocationRequest_()
    : limited_location(false)
    , linear_search_window(0.0)
    , angular_search_window(0.0)
    , pose()
    , relocation_mode(0)  {
    }
  AutoRelocationRequest_(const ContainerAllocator& _alloc)
    : limited_location(false)
    , linear_search_window(0.0)
    , angular_search_window(0.0)
    , pose(_alloc)
    , relocation_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _limited_location_type;
  _limited_location_type limited_location;

   typedef float _linear_search_window_type;
  _linear_search_window_type linear_search_window;

   typedef float _angular_search_window_type;
  _angular_search_window_type angular_search_window;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _relocation_mode_type;
  _relocation_mode_type relocation_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DEFAULT)
  #undef DEFAULT
#endif
#if defined(_WIN32) && defined(FIXED_POSE)
  #undef FIXED_POSE
#endif
#if defined(_WIN32) && defined(FIXED_SEARCH)
  #undef FIXED_SEARCH
#endif
#if defined(_WIN32) && defined(FIXED_POSE_AND_SEARCH)
  #undef FIXED_POSE_AND_SEARCH
#endif

  enum {
    DEFAULT = 0u,
    FIXED_POSE = 1u,
    FIXED_SEARCH = 2u,
    FIXED_POSE_AND_SEARCH = 3u,
  };


  typedef boost::shared_ptr< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AutoRelocationRequest_

typedef ::robint_msgs::AutoRelocationRequest_<std::allocator<void> > AutoRelocationRequest;

typedef boost::shared_ptr< ::robint_msgs::AutoRelocationRequest > AutoRelocationRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::AutoRelocationRequest const> AutoRelocationRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.limited_location == rhs.limited_location &&
    lhs.linear_search_window == rhs.linear_search_window &&
    lhs.angular_search_window == rhs.angular_search_window &&
    lhs.pose == rhs.pose &&
    lhs.relocation_mode == rhs.relocation_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cad0ad4cf80a4f9834d3b591708a326c";
  }

  static const char* value(const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcad0ad4cf80a4f98ULL;
  static const uint64_t static_value2 = 0x34d3b591708a326cULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/AutoRelocationRequest";
  }

  static const char* value(const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool limited_location\n"
"float32 linear_search_window\n"
"float32 angular_search_window\n"
"geometry_msgs/PoseStamped pose\n"
"uint8 relocation_mode\n"
"uint8 DEFAULT=0\n"
"uint8 FIXED_POSE=1\n"
"uint8 FIXED_SEARCH=2\n"
"uint8 FIXED_POSE_AND_SEARCH=3\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limited_location);
      stream.next(m.linear_search_window);
      stream.next(m.angular_search_window);
      stream.next(m.pose);
      stream.next(m.relocation_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoRelocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::AutoRelocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::AutoRelocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "limited_location: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.limited_location);
    s << indent << "linear_search_window: ";
    Printer<float>::stream(s, indent + "  ", v.linear_search_window);
    s << indent << "angular_search_window: ";
    Printer<float>::stream(s, indent + "  ", v.angular_search_window);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "relocation_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relocation_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_AUTORELOCATIONREQUEST_H
