// Generated by gencpp from file robint_msgs/AutoExploreCommand.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_AUTOEXPLORECOMMAND_H
#define ROBINT_MSGS_MESSAGE_AUTOEXPLORECOMMAND_H

#include <ros/service_traits.h>


#include <robint_msgs/AutoExploreCommandRequest.h>
#include <robint_msgs/AutoExploreCommandResponse.h>


namespace robint_msgs
{

struct AutoExploreCommand
{

typedef AutoExploreCommandRequest Request;
typedef AutoExploreCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AutoExploreCommand
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::AutoExploreCommand > {
  static const char* value()
  {
    return "2a8aa6d49f12807a85b62e57d3a33334";
  }

  static const char* value(const ::robint_msgs::AutoExploreCommand&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::AutoExploreCommand > {
  static const char* value()
  {
    return "robint_msgs/AutoExploreCommand";
  }

  static const char* value(const ::robint_msgs::AutoExploreCommand&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::AutoExploreCommandRequest> should match
// service_traits::MD5Sum< ::robint_msgs::AutoExploreCommand >
template<>
struct MD5Sum< ::robint_msgs::AutoExploreCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::AutoExploreCommand >::value();
  }
  static const char* value(const ::robint_msgs::AutoExploreCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::AutoExploreCommandRequest> should match
// service_traits::DataType< ::robint_msgs::AutoExploreCommand >
template<>
struct DataType< ::robint_msgs::AutoExploreCommandRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::AutoExploreCommand >::value();
  }
  static const char* value(const ::robint_msgs::AutoExploreCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::AutoExploreCommandResponse> should match
// service_traits::MD5Sum< ::robint_msgs::AutoExploreCommand >
template<>
struct MD5Sum< ::robint_msgs::AutoExploreCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::AutoExploreCommand >::value();
  }
  static const char* value(const ::robint_msgs::AutoExploreCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::AutoExploreCommandResponse> should match
// service_traits::DataType< ::robint_msgs::AutoExploreCommand >
template<>
struct DataType< ::robint_msgs::AutoExploreCommandResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::AutoExploreCommand >::value();
  }
  static const char* value(const ::robint_msgs::AutoExploreCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_AUTOEXPLORECOMMAND_H
