// Generated by gencpp from file robint_msgs/AutoChargeCommandRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_AUTOCHARGECOMMANDREQUEST_H
#define ROBINT_MSGS_MESSAGE_AUTOCHARGECOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace robint_msgs
{
template <class ContainerAllocator>
struct AutoChargeCommandRequest_
{
  typedef AutoChargeCommandRequest_<ContainerAllocator> Type;

  AutoChargeCommandRequest_()
    : location_name()
    , location_uuid()
    , goal()
    , command(0)  {
    }
  AutoChargeCommandRequest_(const ContainerAllocator& _alloc)
    : location_name(_alloc)
    , location_uuid(_alloc)
    , goal(_alloc)
    , command(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_name_type;
  _location_name_type location_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_uuid_type;
  _location_uuid_type location_uuid;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef uint8_t _command_type;
  _command_type command;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(CONTINUE)
  #undef CONTINUE
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif

  enum {
    START = 0u,
    PAUSE = 1u,
    CONTINUE = 2u,
    STOP = 3u,
  };


  typedef boost::shared_ptr< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AutoChargeCommandRequest_

typedef ::robint_msgs::AutoChargeCommandRequest_<std::allocator<void> > AutoChargeCommandRequest;

typedef boost::shared_ptr< ::robint_msgs::AutoChargeCommandRequest > AutoChargeCommandRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::AutoChargeCommandRequest const> AutoChargeCommandRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.location_name == rhs.location_name &&
    lhs.location_uuid == rhs.location_uuid &&
    lhs.goal == rhs.goal &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00140174a03f898235c30d3fb7a0fdcb";
  }

  static const char* value(const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00140174a03f8982ULL;
  static const uint64_t static_value2 = 0x35c30d3fb7a0fdcbULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/AutoChargeCommandRequest";
  }

  static const char* value(const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string location_name\n"
"string location_uuid\n"
"geometry_msgs/PoseStamped goal\n"
"uint8 command       # 'Start', 'Pause', 'Continue', 'Stop'\n"
"uint8 START=0\n"
"uint8 PAUSE=1\n"
"uint8 CONTINUE=2\n"
"uint8 STOP=3\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location_name);
      stream.next(m.location_uuid);
      stream.next(m.goal);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoChargeCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::AutoChargeCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "location_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location_name);
    s << indent << "location_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location_uuid);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_AUTOCHARGECOMMANDREQUEST_H
