// Generated by gencpp from file robint_msgs/ChangeNavigationState.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_CHANGENAVIGATIONSTATE_H
#define ROBINT_MSGS_MESSAGE_CHANGENAVIGATIONSTATE_H

#include <ros/service_traits.h>


#include <robint_msgs/ChangeNavigationStateRequest.h>
#include <robint_msgs/ChangeNavigationStateResponse.h>


namespace robint_msgs
{

struct ChangeNavigationState
{

typedef ChangeNavigationStateRequest Request;
typedef ChangeNavigationStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeNavigationState
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::ChangeNavigationState > {
  static const char* value()
  {
    return "7c9692bc48992779a3644fe54d668673";
  }

  static const char* value(const ::robint_msgs::ChangeNavigationState&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::ChangeNavigationState > {
  static const char* value()
  {
    return "robint_msgs/ChangeNavigationState";
  }

  static const char* value(const ::robint_msgs::ChangeNavigationState&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::ChangeNavigationStateRequest> should match
// service_traits::MD5Sum< ::robint_msgs::ChangeNavigationState >
template<>
struct MD5Sum< ::robint_msgs::ChangeNavigationStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::ChangeNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeNavigationStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::ChangeNavigationStateRequest> should match
// service_traits::DataType< ::robint_msgs::ChangeNavigationState >
template<>
struct DataType< ::robint_msgs::ChangeNavigationStateRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::ChangeNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeNavigationStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::ChangeNavigationStateResponse> should match
// service_traits::MD5Sum< ::robint_msgs::ChangeNavigationState >
template<>
struct MD5Sum< ::robint_msgs::ChangeNavigationStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::ChangeNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeNavigationStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::ChangeNavigationStateResponse> should match
// service_traits::DataType< ::robint_msgs::ChangeNavigationState >
template<>
struct DataType< ::robint_msgs::ChangeNavigationStateResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::ChangeNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeNavigationStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_CHANGENAVIGATIONSTATE_H
