// Generated by gencpp from file robint_msgs/ChangeUndockState.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_CHANGEUNDOCKSTATE_H
#define ROBINT_MSGS_MESSAGE_CHANGEUNDOCKSTATE_H

#include <ros/service_traits.h>


#include <robint_msgs/ChangeUndockStateRequest.h>
#include <robint_msgs/ChangeUndockStateResponse.h>


namespace robint_msgs
{

struct ChangeUndockState
{

typedef ChangeUndockStateRequest Request;
typedef ChangeUndockStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeUndockState
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::ChangeUndockState > {
  static const char* value()
  {
    return "1df2b32e00d9659a7afd807940e0bc0e";
  }

  static const char* value(const ::robint_msgs::ChangeUndockState&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::ChangeUndockState > {
  static const char* value()
  {
    return "robint_msgs/ChangeUndockState";
  }

  static const char* value(const ::robint_msgs::ChangeUndockState&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::ChangeUndockStateRequest> should match
// service_traits::MD5Sum< ::robint_msgs::ChangeUndockState >
template<>
struct MD5Sum< ::robint_msgs::ChangeUndockStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::ChangeUndockState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeUndockStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::ChangeUndockStateRequest> should match
// service_traits::DataType< ::robint_msgs::ChangeUndockState >
template<>
struct DataType< ::robint_msgs::ChangeUndockStateRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::ChangeUndockState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeUndockStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::ChangeUndockStateResponse> should match
// service_traits::MD5Sum< ::robint_msgs::ChangeUndockState >
template<>
struct MD5Sum< ::robint_msgs::ChangeUndockStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::ChangeUndockState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeUndockStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::ChangeUndockStateResponse> should match
// service_traits::DataType< ::robint_msgs::ChangeUndockState >
template<>
struct DataType< ::robint_msgs::ChangeUndockStateResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::ChangeUndockState >::value();
  }
  static const char* value(const ::robint_msgs::ChangeUndockStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_CHANGEUNDOCKSTATE_H
