// Generated by gencpp from file robint_msgs/CleaningAreaInfo.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_CLEANINGAREAINFO_H
#define ROBINT_MSGS_MESSAGE_CLEANINGAREAINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct CleaningAreaInfo_
{
  typedef CleaningAreaInfo_<ContainerAllocator> Type;

  CleaningAreaInfo_()
    : uuid()
    , name()
    , map_uuid()
    , group_uuid()
    , area(0.0)  {
    }
  CleaningAreaInfo_(const ContainerAllocator& _alloc)
    : uuid(_alloc)
    , name(_alloc)
    , map_uuid(_alloc)
    , group_uuid(_alloc)
    , area(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _uuid_type;
  _uuid_type uuid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_uuid_type;
  _map_uuid_type map_uuid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _group_uuid_type;
  _group_uuid_type group_uuid;

   typedef float _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> const> ConstPtr;

}; // struct CleaningAreaInfo_

typedef ::robint_msgs::CleaningAreaInfo_<std::allocator<void> > CleaningAreaInfo;

typedef boost::shared_ptr< ::robint_msgs::CleaningAreaInfo > CleaningAreaInfoPtr;
typedef boost::shared_ptr< ::robint_msgs::CleaningAreaInfo const> CleaningAreaInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator1> & lhs, const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator2> & rhs)
{
  return lhs.uuid == rhs.uuid &&
    lhs.name == rhs.name &&
    lhs.map_uuid == rhs.map_uuid &&
    lhs.group_uuid == rhs.group_uuid &&
    lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator1> & lhs, const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44deeac11f18e06ad9c20de2970c1c5d";
  }

  static const char* value(const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44deeac11f18e06aULL;
  static const uint64_t static_value2 = 0xd9c20de2970c1c5dULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/CleaningAreaInfo";
  }

  static const char* value(const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string uuid\n"
"string name\n"
"string map_uuid\n"
"string group_uuid\n"
"float32 area  # m * m\n"
;
  }

  static const char* value(const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uuid);
      stream.next(m.name);
      stream.next(m.map_uuid);
      stream.next(m.group_uuid);
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CleaningAreaInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::CleaningAreaInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::CleaningAreaInfo_<ContainerAllocator>& v)
  {
    s << indent << "uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.uuid);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "map_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_uuid);
    s << indent << "group_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.group_uuid);
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_CLEANINGAREAINFO_H
