// Generated by gencpp from file robint_msgs/Command.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_COMMAND_H
#define ROBINT_MSGS_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <robint_msgs/CommandRequest.h>
#include <robint_msgs/CommandResponse.h>


namespace robint_msgs
{

struct Command
{

typedef CommandRequest Request;
typedef CommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Command
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::Command > {
  static const char* value()
  {
    return "5d04c39ce79551e9cd033e644af5293f";
  }

  static const char* value(const ::robint_msgs::Command&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::Command > {
  static const char* value()
  {
    return "robint_msgs/Command";
  }

  static const char* value(const ::robint_msgs::Command&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::CommandRequest> should match
// service_traits::MD5Sum< ::robint_msgs::Command >
template<>
struct MD5Sum< ::robint_msgs::CommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::Command >::value();
  }
  static const char* value(const ::robint_msgs::CommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::CommandRequest> should match
// service_traits::DataType< ::robint_msgs::Command >
template<>
struct DataType< ::robint_msgs::CommandRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::Command >::value();
  }
  static const char* value(const ::robint_msgs::CommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::CommandResponse> should match
// service_traits::MD5Sum< ::robint_msgs::Command >
template<>
struct MD5Sum< ::robint_msgs::CommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::Command >::value();
  }
  static const char* value(const ::robint_msgs::CommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::CommandResponse> should match
// service_traits::DataType< ::robint_msgs::Command >
template<>
struct DataType< ::robint_msgs::CommandResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::Command >::value();
  }
  static const char* value(const ::robint_msgs::CommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_COMMAND_H
