// Generated by gencpp from file robint_msgs/DeleteLocationListRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_DELETELOCATIONLISTREQUEST_H
#define ROBINT_MSGS_MESSAGE_DELETELOCATIONLISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct DeleteLocationListRequest_
{
  typedef DeleteLocationListRequest_<ContainerAllocator> Type;

  DeleteLocationListRequest_()
    : map_name()
    , map_uuid()
    , group_uuid()
    , location_uuid_list()  {
    }
  DeleteLocationListRequest_(const ContainerAllocator& _alloc)
    : map_name(_alloc)
    , map_uuid(_alloc)
    , group_uuid(_alloc)
    , location_uuid_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_name_type;
  _map_name_type map_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_uuid_type;
  _map_uuid_type map_uuid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _group_uuid_type;
  _group_uuid_type group_uuid;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _location_uuid_list_type;
  _location_uuid_list_type location_uuid_list;





  typedef boost::shared_ptr< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteLocationListRequest_

typedef ::robint_msgs::DeleteLocationListRequest_<std::allocator<void> > DeleteLocationListRequest;

typedef boost::shared_ptr< ::robint_msgs::DeleteLocationListRequest > DeleteLocationListRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::DeleteLocationListRequest const> DeleteLocationListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_name == rhs.map_name &&
    lhs.map_uuid == rhs.map_uuid &&
    lhs.group_uuid == rhs.group_uuid &&
    lhs.location_uuid_list == rhs.location_uuid_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09ca208b7a82bbdedef18c3575381912";
  }

  static const char* value(const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09ca208b7a82bbdeULL;
  static const uint64_t static_value2 = 0xdef18c3575381912ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/DeleteLocationListRequest";
  }

  static const char* value(const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_name\n"
"string map_uuid\n"
"string group_uuid\n"
"string[] location_uuid_list\n"
;
  }

  static const char* value(const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_name);
      stream.next(m.map_uuid);
      stream.next(m.group_uuid);
      stream.next(m.location_uuid_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteLocationListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::DeleteLocationListRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_name);
    s << indent << "map_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_uuid);
    s << indent << "group_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.group_uuid);
    s << indent << "location_uuid_list[]" << std::endl;
    for (size_t i = 0; i < v.location_uuid_list.size(); ++i)
    {
      s << indent << "  location_uuid_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location_uuid_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_DELETELOCATIONLISTREQUEST_H
