// Generated by gencpp from file robint_msgs/DeleteLocation.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_DELETELOCATION_H
#define ROBINT_MSGS_MESSAGE_DELETELOCATION_H

#include <ros/service_traits.h>


#include <robint_msgs/DeleteLocationRequest.h>
#include <robint_msgs/DeleteLocationResponse.h>


namespace robint_msgs
{

struct DeleteLocation
{

typedef DeleteLocationRequest Request;
typedef DeleteLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteLocation
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::DeleteLocation > {
  static const char* value()
  {
    return "e455ff67939cb430aa8c8b048159a412";
  }

  static const char* value(const ::robint_msgs::DeleteLocation&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::DeleteLocation > {
  static const char* value()
  {
    return "robint_msgs/DeleteLocation";
  }

  static const char* value(const ::robint_msgs::DeleteLocation&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::DeleteLocationRequest> should match
// service_traits::MD5Sum< ::robint_msgs::DeleteLocation >
template<>
struct MD5Sum< ::robint_msgs::DeleteLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::DeleteLocation >::value();
  }
  static const char* value(const ::robint_msgs::DeleteLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::DeleteLocationRequest> should match
// service_traits::DataType< ::robint_msgs::DeleteLocation >
template<>
struct DataType< ::robint_msgs::DeleteLocationRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::DeleteLocation >::value();
  }
  static const char* value(const ::robint_msgs::DeleteLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::DeleteLocationResponse> should match
// service_traits::MD5Sum< ::robint_msgs::DeleteLocation >
template<>
struct MD5Sum< ::robint_msgs::DeleteLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::DeleteLocation >::value();
  }
  static const char* value(const ::robint_msgs::DeleteLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::DeleteLocationResponse> should match
// service_traits::DataType< ::robint_msgs::DeleteLocation >
template<>
struct DataType< ::robint_msgs::DeleteLocationResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::DeleteLocation >::value();
  }
  static const char* value(const ::robint_msgs::DeleteLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_DELETELOCATION_H
