// Generated by gencpp from file robint_msgs/GenerateCleaningPathResponse.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GENERATECLEANINGPATHRESPONSE_H
#define ROBINT_MSGS_MESSAGE_GENERATECLEANINGPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robint_msgs/PathWithPoint.h>

namespace robint_msgs
{
template <class ContainerAllocator>
struct GenerateCleaningPathResponse_
{
  typedef GenerateCleaningPathResponse_<ContainerAllocator> Type;

  GenerateCleaningPathResponse_()
    : coordinate_mode(0)
    , paths()
    , success(false)
    , error_code(0)
    , message()  {
    }
  GenerateCleaningPathResponse_(const ContainerAllocator& _alloc)
    : coordinate_mode(0)
    , paths(_alloc)
    , success(false)
    , error_code(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _coordinate_mode_type;
  _coordinate_mode_type coordinate_mode;

   typedef std::vector< ::robint_msgs::PathWithPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::robint_msgs::PathWithPoint_<ContainerAllocator> >> _paths_type;
  _paths_type paths;

   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateCleaningPathResponse_

typedef ::robint_msgs::GenerateCleaningPathResponse_<std::allocator<void> > GenerateCleaningPathResponse;

typedef boost::shared_ptr< ::robint_msgs::GenerateCleaningPathResponse > GenerateCleaningPathResponsePtr;
typedef boost::shared_ptr< ::robint_msgs::GenerateCleaningPathResponse const> GenerateCleaningPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator1> & lhs, const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.coordinate_mode == rhs.coordinate_mode &&
    lhs.paths == rhs.paths &&
    lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator1> & lhs, const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c96c0178ee444b2dfcbd51830ac65d31";
  }

  static const char* value(const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc96c0178ee444b2dULL;
  static const uint64_t static_value2 = 0xfcbd51830ac65d31ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/GenerateCleaningPathResponse";
  }

  static const char* value(const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 coordinate_mode\n"
"PathWithPoint[] paths\n"
"bool success\n"
"uint8 error_code\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: robint_msgs/PathWithPoint\n"
"uint32 id\n"
"string type\n"
"geometry_msgs/Point[] points\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinate_mode);
      stream.next(m.paths);
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateCleaningPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::GenerateCleaningPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "coordinate_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.coordinate_mode);
    s << indent << "paths[]" << std::endl;
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      s << indent << "  paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robint_msgs::PathWithPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.paths[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GENERATECLEANINGPATHRESPONSE_H
