// Generated by gencpp from file robint_msgs/GetCleaningAreaListRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETCLEANINGAREALISTREQUEST_H
#define ROBINT_MSGS_MESSAGE_GETCLEANINGAREALISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct GetCleaningAreaListRequest_
{
  typedef GetCleaningAreaListRequest_<ContainerAllocator> Type;

  GetCleaningAreaListRequest_()
    : map_uuid()
    , coordinate_mode(0)  {
    }
  GetCleaningAreaListRequest_(const ContainerAllocator& _alloc)
    : map_uuid(_alloc)
    , coordinate_mode(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_uuid_type;
  _map_uuid_type map_uuid;

   typedef uint8_t _coordinate_mode_type;
  _coordinate_mode_type coordinate_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IMAGE)
  #undef IMAGE
#endif
#if defined(_WIN32) && defined(WORLD)
  #undef WORLD
#endif

  enum {
    IMAGE = 0u,
    WORLD = 1u,
  };


  typedef boost::shared_ptr< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCleaningAreaListRequest_

typedef ::robint_msgs::GetCleaningAreaListRequest_<std::allocator<void> > GetCleaningAreaListRequest;

typedef boost::shared_ptr< ::robint_msgs::GetCleaningAreaListRequest > GetCleaningAreaListRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::GetCleaningAreaListRequest const> GetCleaningAreaListRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_uuid == rhs.map_uuid &&
    lhs.coordinate_mode == rhs.coordinate_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c005ae0ccdf75fba08d9abbc1cea2fb8";
  }

  static const char* value(const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc005ae0ccdf75fbaULL;
  static const uint64_t static_value2 = 0x08d9abbc1cea2fb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/GetCleaningAreaListRequest";
  }

  static const char* value(const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_uuid\n"
"uint8 coordinate_mode\n"
"uint8 IMAGE=0\n"
"uint8 WORLD=1\n"
;
  }

  static const char* value(const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_uuid);
      stream.next(m.coordinate_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCleaningAreaListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::GetCleaningAreaListRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_uuid);
    s << indent << "coordinate_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.coordinate_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETCLEANINGAREALISTREQUEST_H
