// Generated by gencpp from file robint_msgs/GetCurrentRobotPose.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETCURRENTROBOTPOSE_H
#define ROBINT_MSGS_MESSAGE_GETCURRENTROBOTPOSE_H

#include <ros/service_traits.h>


#include <robint_msgs/GetCurrentRobotPoseRequest.h>
#include <robint_msgs/GetCurrentRobotPoseResponse.h>


namespace robint_msgs
{

struct GetCurrentRobotPose
{

typedef GetCurrentRobotPoseRequest Request;
typedef GetCurrentRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentRobotPose
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetCurrentRobotPose > {
  static const char* value()
  {
    return "e893e35ee69a289c4ba9dfb64de7b851";
  }

  static const char* value(const ::robint_msgs::GetCurrentRobotPose&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetCurrentRobotPose > {
  static const char* value()
  {
    return "robint_msgs/GetCurrentRobotPose";
  }

  static const char* value(const ::robint_msgs::GetCurrentRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetCurrentRobotPoseRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetCurrentRobotPose >
template<>
struct MD5Sum< ::robint_msgs::GetCurrentRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetCurrentRobotPose >::value();
  }
  static const char* value(const ::robint_msgs::GetCurrentRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetCurrentRobotPoseRequest> should match
// service_traits::DataType< ::robint_msgs::GetCurrentRobotPose >
template<>
struct DataType< ::robint_msgs::GetCurrentRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetCurrentRobotPose >::value();
  }
  static const char* value(const ::robint_msgs::GetCurrentRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetCurrentRobotPoseResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetCurrentRobotPose >
template<>
struct MD5Sum< ::robint_msgs::GetCurrentRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetCurrentRobotPose >::value();
  }
  static const char* value(const ::robint_msgs::GetCurrentRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetCurrentRobotPoseResponse> should match
// service_traits::DataType< ::robint_msgs::GetCurrentRobotPose >
template<>
struct DataType< ::robint_msgs::GetCurrentRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetCurrentRobotPose >::value();
  }
  static const char* value(const ::robint_msgs::GetCurrentRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETCURRENTROBOTPOSE_H
