// Generated by gencpp from file robint_msgs/GetDetailedNavigationInfo.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETDETAILEDNAVIGATIONINFO_H
#define ROBINT_MSGS_MESSAGE_GETDETAILEDNAVIGATIONINFO_H

#include <ros/service_traits.h>


#include <robint_msgs/GetDetailedNavigationInfoRequest.h>
#include <robint_msgs/GetDetailedNavigationInfoResponse.h>


namespace robint_msgs
{

struct GetDetailedNavigationInfo
{

typedef GetDetailedNavigationInfoRequest Request;
typedef GetDetailedNavigationInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDetailedNavigationInfo
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetDetailedNavigationInfo > {
  static const char* value()
  {
    return "d40b5c7df15504a3cb8d5081f8acd091";
  }

  static const char* value(const ::robint_msgs::GetDetailedNavigationInfo&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetDetailedNavigationInfo > {
  static const char* value()
  {
    return "robint_msgs/GetDetailedNavigationInfo";
  }

  static const char* value(const ::robint_msgs::GetDetailedNavigationInfo&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetDetailedNavigationInfoRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetDetailedNavigationInfo >
template<>
struct MD5Sum< ::robint_msgs::GetDetailedNavigationInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetDetailedNavigationInfo >::value();
  }
  static const char* value(const ::robint_msgs::GetDetailedNavigationInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetDetailedNavigationInfoRequest> should match
// service_traits::DataType< ::robint_msgs::GetDetailedNavigationInfo >
template<>
struct DataType< ::robint_msgs::GetDetailedNavigationInfoRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetDetailedNavigationInfo >::value();
  }
  static const char* value(const ::robint_msgs::GetDetailedNavigationInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetDetailedNavigationInfoResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetDetailedNavigationInfo >
template<>
struct MD5Sum< ::robint_msgs::GetDetailedNavigationInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetDetailedNavigationInfo >::value();
  }
  static const char* value(const ::robint_msgs::GetDetailedNavigationInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetDetailedNavigationInfoResponse> should match
// service_traits::DataType< ::robint_msgs::GetDetailedNavigationInfo >
template<>
struct DataType< ::robint_msgs::GetDetailedNavigationInfoResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetDetailedNavigationInfo >::value();
  }
  static const char* value(const ::robint_msgs::GetDetailedNavigationInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETDETAILEDNAVIGATIONINFO_H
