// Generated by gencpp from file robint_msgs/GetEmbeddingVersionResponse.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETEMBEDDINGVERSIONRESPONSE_H
#define ROBINT_MSGS_MESSAGE_GETEMBEDDINGVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct GetEmbeddingVersionResponse_
{
  typedef GetEmbeddingVersionResponse_<ContainerAllocator> Type;

  GetEmbeddingVersionResponse_()
    : protocal_version()
    , success(false)
    , error_code(0)  {
    }
  GetEmbeddingVersionResponse_(const ContainerAllocator& _alloc)
    : protocal_version(_alloc)
    , success(false)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _protocal_version_type;
  _protocal_version_type protocal_version;

   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEmbeddingVersionResponse_

typedef ::robint_msgs::GetEmbeddingVersionResponse_<std::allocator<void> > GetEmbeddingVersionResponse;

typedef boost::shared_ptr< ::robint_msgs::GetEmbeddingVersionResponse > GetEmbeddingVersionResponsePtr;
typedef boost::shared_ptr< ::robint_msgs::GetEmbeddingVersionResponse const> GetEmbeddingVersionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator1> & lhs, const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.protocal_version == rhs.protocal_version &&
    lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator1> & lhs, const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7b90ba6d5e0d773d0e5bf8c701d7b10";
  }

  static const char* value(const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7b90ba6d5e0d773ULL;
  static const uint64_t static_value2 = 0xd0e5bf8c701d7b10ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/GetEmbeddingVersionResponse";
  }

  static const char* value(const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string protocal_version\n"
"bool success\n"
"uint8 error_code\n"
;
  }

  static const char* value(const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.protocal_version);
      stream.next(m.success);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEmbeddingVersionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::GetEmbeddingVersionResponse_<ContainerAllocator>& v)
  {
    s << indent << "protocal_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.protocal_version);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETEMBEDDINGVERSIONRESPONSE_H
