// Generated by gencpp from file robint_msgs/GetMapInfoRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETMAPINFOREQUEST_H
#define ROBINT_MSGS_MESSAGE_GETMAPINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct GetMapInfoRequest_
{
  typedef GetMapInfoRequest_<ContainerAllocator> Type;

  GetMapInfoRequest_()
    : map_uuid()  {
    }
  GetMapInfoRequest_(const ContainerAllocator& _alloc)
    : map_uuid(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_uuid_type;
  _map_uuid_type map_uuid;





  typedef boost::shared_ptr< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapInfoRequest_

typedef ::robint_msgs::GetMapInfoRequest_<std::allocator<void> > GetMapInfoRequest;

typedef boost::shared_ptr< ::robint_msgs::GetMapInfoRequest > GetMapInfoRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::GetMapInfoRequest const> GetMapInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_uuid == rhs.map_uuid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc5bf00fcd212651e6eaf61320fdb627";
  }

  static const char* value(const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc5bf00fcd212651ULL;
  static const uint64_t static_value2 = 0xe6eaf61320fdb627ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/GetMapInfoRequest";
  }

  static const char* value(const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_uuid\n"
;
  }

  static const char* value(const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_uuid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::GetMapInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::GetMapInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_uuid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETMAPINFOREQUEST_H
