// Generated by gencpp from file robint_msgs/GetMap.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETMAP_H
#define ROBINT_MSGS_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <robint_msgs/GetMapRequest.h>
#include <robint_msgs/GetMapResponse.h>


namespace robint_msgs
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetMap > {
  static const char* value()
  {
    return "c145072a51e966562a8b55da3beeb5d5";
  }

  static const char* value(const ::robint_msgs::GetMap&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetMap > {
  static const char* value()
  {
    return "robint_msgs/GetMap";
  }

  static const char* value(const ::robint_msgs::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetMapRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetMap >
template<>
struct MD5Sum< ::robint_msgs::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetMap >::value();
  }
  static const char* value(const ::robint_msgs::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetMapRequest> should match
// service_traits::DataType< ::robint_msgs::GetMap >
template<>
struct DataType< ::robint_msgs::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetMap >::value();
  }
  static const char* value(const ::robint_msgs::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetMapResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetMap >
template<>
struct MD5Sum< ::robint_msgs::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetMap >::value();
  }
  static const char* value(const ::robint_msgs::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetMapResponse> should match
// service_traits::DataType< ::robint_msgs::GetMap >
template<>
struct DataType< ::robint_msgs::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetMap >::value();
  }
  static const char* value(const ::robint_msgs::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETMAP_H
