// Generated by gencpp from file robint_msgs/GetNavigationState.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETNAVIGATIONSTATE_H
#define ROBINT_MSGS_MESSAGE_GETNAVIGATIONSTATE_H

#include <ros/service_traits.h>


#include <robint_msgs/GetNavigationStateRequest.h>
#include <robint_msgs/GetNavigationStateResponse.h>


namespace robint_msgs
{

struct GetNavigationState
{

typedef GetNavigationStateRequest Request;
typedef GetNavigationStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNavigationState
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetNavigationState > {
  static const char* value()
  {
    return "f3610dd921b0fb5ea6025bf47fc93512";
  }

  static const char* value(const ::robint_msgs::GetNavigationState&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetNavigationState > {
  static const char* value()
  {
    return "robint_msgs/GetNavigationState";
  }

  static const char* value(const ::robint_msgs::GetNavigationState&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetNavigationStateRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetNavigationState >
template<>
struct MD5Sum< ::robint_msgs::GetNavigationStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::GetNavigationStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetNavigationStateRequest> should match
// service_traits::DataType< ::robint_msgs::GetNavigationState >
template<>
struct DataType< ::robint_msgs::GetNavigationStateRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::GetNavigationStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetNavigationStateResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetNavigationState >
template<>
struct MD5Sum< ::robint_msgs::GetNavigationStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::GetNavigationStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetNavigationStateResponse> should match
// service_traits::DataType< ::robint_msgs::GetNavigationState >
template<>
struct DataType< ::robint_msgs::GetNavigationStateResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetNavigationState >::value();
  }
  static const char* value(const ::robint_msgs::GetNavigationStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETNAVIGATIONSTATE_H
