// Generated by gencpp from file robint_msgs/GetParamsResponse.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETPARAMSRESPONSE_H
#define ROBINT_MSGS_MESSAGE_GETPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robint_msgs/Param.h>

namespace robint_msgs
{
template <class ContainerAllocator>
struct GetParamsResponse_
{
  typedef GetParamsResponse_<ContainerAllocator> Type;

  GetParamsResponse_()
    : params()
    , success(false)
    , error_code(0)
    , message()  {
    }
  GetParamsResponse_(const ContainerAllocator& _alloc)
    : params(_alloc)
    , success(false)
    , error_code(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robint_msgs::Param_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::robint_msgs::Param_<ContainerAllocator> >> _params_type;
  _params_type params;

   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robint_msgs::GetParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::GetParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetParamsResponse_

typedef ::robint_msgs::GetParamsResponse_<std::allocator<void> > GetParamsResponse;

typedef boost::shared_ptr< ::robint_msgs::GetParamsResponse > GetParamsResponsePtr;
typedef boost::shared_ptr< ::robint_msgs::GetParamsResponse const> GetParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::GetParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::GetParamsResponse_<ContainerAllocator1> & lhs, const ::robint_msgs::GetParamsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.params == rhs.params &&
    lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::GetParamsResponse_<ContainerAllocator1> & lhs, const ::robint_msgs::GetParamsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::GetParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::GetParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::GetParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f46bca7764e7343336267c107612e4d";
  }

  static const char* value(const ::robint_msgs::GetParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f46bca7764e7343ULL;
  static const uint64_t static_value2 = 0x336267c107612e4dULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/GetParamsResponse";
  }

  static const char* value(const ::robint_msgs::GetParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Param[] params\n"
"bool success\n"
"uint8 error_code\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: robint_msgs/Param\n"
"string name\n"
"string type    # \"String\", \"Bool\", \"Float\", \"Int\"\n"
"string value\n"
;
  }

  static const char* value(const ::robint_msgs::GetParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params);
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::GetParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::GetParamsResponse_<ContainerAllocator>& v)
  {
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robint_msgs::Param_<ContainerAllocator> >::stream(s, indent + "    ", v.params[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETPARAMSRESPONSE_H
