// Generated by gencpp from file robint_msgs/GetPlan.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETPLAN_H
#define ROBINT_MSGS_MESSAGE_GETPLAN_H

#include <ros/service_traits.h>


#include <robint_msgs/GetPlanRequest.h>
#include <robint_msgs/GetPlanResponse.h>


namespace robint_msgs
{

struct GetPlan
{

typedef GetPlanRequest Request;
typedef GetPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlan
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetPlan > {
  static const char* value()
  {
    return "a932883b63c9b3eddafe2113df5fe719";
  }

  static const char* value(const ::robint_msgs::GetPlan&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetPlan > {
  static const char* value()
  {
    return "robint_msgs/GetPlan";
  }

  static const char* value(const ::robint_msgs::GetPlan&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetPlanRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetPlan >
template<>
struct MD5Sum< ::robint_msgs::GetPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetPlan >::value();
  }
  static const char* value(const ::robint_msgs::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetPlanRequest> should match
// service_traits::DataType< ::robint_msgs::GetPlan >
template<>
struct DataType< ::robint_msgs::GetPlanRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetPlan >::value();
  }
  static const char* value(const ::robint_msgs::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetPlanResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetPlan >
template<>
struct MD5Sum< ::robint_msgs::GetPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetPlan >::value();
  }
  static const char* value(const ::robint_msgs::GetPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetPlanResponse> should match
// service_traits::DataType< ::robint_msgs::GetPlan >
template<>
struct DataType< ::robint_msgs::GetPlanResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetPlan >::value();
  }
  static const char* value(const ::robint_msgs::GetPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETPLAN_H
