// Generated by gencpp from file robint_msgs/GetTrajectoryPoint.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETTRAJECTORYPOINT_H
#define ROBINT_MSGS_MESSAGE_GETTRAJECTORYPOINT_H

#include <ros/service_traits.h>


#include <robint_msgs/GetTrajectoryPointRequest.h>
#include <robint_msgs/GetTrajectoryPointResponse.h>


namespace robint_msgs
{

struct GetTrajectoryPoint
{

typedef GetTrajectoryPointRequest Request;
typedef GetTrajectoryPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrajectoryPoint
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetTrajectoryPoint > {
  static const char* value()
  {
    return "8fd56019054effcf13a55a60fa14c24c";
  }

  static const char* value(const ::robint_msgs::GetTrajectoryPoint&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetTrajectoryPoint > {
  static const char* value()
  {
    return "robint_msgs/GetTrajectoryPoint";
  }

  static const char* value(const ::robint_msgs::GetTrajectoryPoint&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetTrajectoryPointRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetTrajectoryPoint >
template<>
struct MD5Sum< ::robint_msgs::GetTrajectoryPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetTrajectoryPoint >::value();
  }
  static const char* value(const ::robint_msgs::GetTrajectoryPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetTrajectoryPointRequest> should match
// service_traits::DataType< ::robint_msgs::GetTrajectoryPoint >
template<>
struct DataType< ::robint_msgs::GetTrajectoryPointRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetTrajectoryPoint >::value();
  }
  static const char* value(const ::robint_msgs::GetTrajectoryPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetTrajectoryPointResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetTrajectoryPoint >
template<>
struct MD5Sum< ::robint_msgs::GetTrajectoryPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetTrajectoryPoint >::value();
  }
  static const char* value(const ::robint_msgs::GetTrajectoryPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetTrajectoryPointResponse> should match
// service_traits::DataType< ::robint_msgs::GetTrajectoryPoint >
template<>
struct DataType< ::robint_msgs::GetTrajectoryPointResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetTrajectoryPoint >::value();
  }
  static const char* value(const ::robint_msgs::GetTrajectoryPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETTRAJECTORYPOINT_H
