// Generated by gencpp from file robint_msgs/GetZone.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_GETZONE_H
#define ROBINT_MSGS_MESSAGE_GETZONE_H

#include <ros/service_traits.h>


#include <robint_msgs/GetZoneRequest.h>
#include <robint_msgs/GetZoneResponse.h>


namespace robint_msgs
{

struct GetZone
{

typedef GetZoneRequest Request;
typedef GetZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetZone
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::GetZone > {
  static const char* value()
  {
    return "3e8c73a28008489ea806c0e13cd661f0";
  }

  static const char* value(const ::robint_msgs::GetZone&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::GetZone > {
  static const char* value()
  {
    return "robint_msgs/GetZone";
  }

  static const char* value(const ::robint_msgs::GetZone&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::GetZoneRequest> should match
// service_traits::MD5Sum< ::robint_msgs::GetZone >
template<>
struct MD5Sum< ::robint_msgs::GetZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetZone >::value();
  }
  static const char* value(const ::robint_msgs::GetZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetZoneRequest> should match
// service_traits::DataType< ::robint_msgs::GetZone >
template<>
struct DataType< ::robint_msgs::GetZoneRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetZone >::value();
  }
  static const char* value(const ::robint_msgs::GetZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::GetZoneResponse> should match
// service_traits::MD5Sum< ::robint_msgs::GetZone >
template<>
struct MD5Sum< ::robint_msgs::GetZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::GetZone >::value();
  }
  static const char* value(const ::robint_msgs::GetZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::GetZoneResponse> should match
// service_traits::DataType< ::robint_msgs::GetZone >
template<>
struct DataType< ::robint_msgs::GetZoneResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::GetZone >::value();
  }
  static const char* value(const ::robint_msgs::GetZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_GETZONE_H
