// Generated by gencpp from file robint_msgs/MappingState.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_MAPPINGSTATE_H
#define ROBINT_MSGS_MESSAGE_MAPPINGSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robint_msgs/TaskStateHeader.h>
#include <nav_msgs/OccupancyGrid.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/PoseStamped.h>

namespace robint_msgs
{
template <class ContainerAllocator>
struct MappingState_
{
  typedef MappingState_<ContainerAllocator> Type;

  MappingState_()
    : header()
    , map_data()
    , image_pose()
    , pose()
    , r_state(0)
    , r_feedback(0)  {
    }
  MappingState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , map_data(_alloc)
    , image_pose(_alloc)
    , pose(_alloc)
    , r_state(0)
    , r_feedback(0)  {
  (void)_alloc;
    }



   typedef  ::robint_msgs::TaskStateHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_data_type;
  _map_data_type map_data;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _image_pose_type;
  _image_pose_type image_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _r_state_type;
  _r_state_type r_state;

   typedef uint8_t _r_feedback_type;
  _r_feedback_type r_feedback;





  typedef boost::shared_ptr< ::robint_msgs::MappingState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::MappingState_<ContainerAllocator> const> ConstPtr;

}; // struct MappingState_

typedef ::robint_msgs::MappingState_<std::allocator<void> > MappingState;

typedef boost::shared_ptr< ::robint_msgs::MappingState > MappingStatePtr;
typedef boost::shared_ptr< ::robint_msgs::MappingState const> MappingStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::MappingState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::MappingState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::MappingState_<ContainerAllocator1> & lhs, const ::robint_msgs::MappingState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.map_data == rhs.map_data &&
    lhs.image_pose == rhs.image_pose &&
    lhs.pose == rhs.pose &&
    lhs.r_state == rhs.r_state &&
    lhs.r_feedback == rhs.r_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::MappingState_<ContainerAllocator1> & lhs, const ::robint_msgs::MappingState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::MappingState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::MappingState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::MappingState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::MappingState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::MappingState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::MappingState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::MappingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eda50e62935bde588e7b2e9550b69559";
  }

  static const char* value(const ::robint_msgs::MappingState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeda50e62935bde58ULL;
  static const uint64_t static_value2 = 0x8e7b2e9550b69559ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::MappingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/MappingState";
  }

  static const char* value(const ::robint_msgs::MappingState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::MappingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TaskStateHeader header\n"
"nav_msgs/OccupancyGrid map_data\n"
"geometry_msgs/Pose2D image_pose\n"
"geometry_msgs/PoseStamped pose\n"
"uint8 r_state\n"
"uint8 r_feedback\n"
"================================================================================\n"
"MSG: robint_msgs/TaskStateHeader\n"
"bool activate  # 该任务是否处于激活状态\n"
"time start_time\n"
"time stop_time\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
;
  }

  static const char* value(const ::robint_msgs::MappingState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::MappingState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.map_data);
      stream.next(m.image_pose);
      stream.next(m.pose);
      stream.next(m.r_state);
      stream.next(m.r_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MappingState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::MappingState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::MappingState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::robint_msgs::TaskStateHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "map_data: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map_data);
    s << indent << "image_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.image_pose);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "r_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r_state);
    s << indent << "r_feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_MAPPINGSTATE_H
