// Generated by gencpp from file robint_msgs/MotionCommandRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_MOTIONCOMMANDREQUEST_H
#define ROBINT_MSGS_MESSAGE_MOTIONCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct MotionCommandRequest_
{
  typedef MotionCommandRequest_<ContainerAllocator> Type;

  MotionCommandRequest_()
    : command(0)
    , type(0)
    , dist(0.0)
    , theta_degree(0.0)  {
    }
  MotionCommandRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , type(0)
    , dist(0.0)
    , theta_degree(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef uint8_t _type_type;
  _type_type type;

   typedef float _dist_type;
  _dist_type dist;

   typedef float _theta_degree_type;
  _theta_degree_type theta_degree;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(CONTINUE)
  #undef CONTINUE
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(MOVE)
  #undef MOVE
#endif
#if defined(_WIN32) && defined(ROTATE)
  #undef ROTATE
#endif
#if defined(_WIN32) && defined(CALL)
  #undef CALL
#endif

  enum {
    START = 0u,
    PAUSE = 1u,
    CONTINUE = 2u,
    STOP = 3u,
    MOVE = 11u,
    ROTATE = 12u,
    CALL = 13u,
  };


  typedef boost::shared_ptr< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MotionCommandRequest_

typedef ::robint_msgs::MotionCommandRequest_<std::allocator<void> > MotionCommandRequest;

typedef boost::shared_ptr< ::robint_msgs::MotionCommandRequest > MotionCommandRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::MotionCommandRequest const> MotionCommandRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::MotionCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::MotionCommandRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::MotionCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.type == rhs.type &&
    lhs.dist == rhs.dist &&
    lhs.theta_degree == rhs.theta_degree;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::MotionCommandRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::MotionCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f02bd641137f690da38fc964b1acc15b";
  }

  static const char* value(const ::robint_msgs::MotionCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf02bd641137f690dULL;
  static const uint64_t static_value2 = 0xa38fc964b1acc15bULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/MotionCommandRequest";
  }

  static const char* value(const ::robint_msgs::MotionCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 command       # 'Start', 'Pause', 'Continue', 'Stop'\n"
"uint8 START=0\n"
"uint8 PAUSE=1\n"
"uint8 CONTINUE=2\n"
"uint8 STOP=3\n"
"uint8 type\n"
"uint8 MOVE=11\n"
"uint8 ROTATE=12\n"
"uint8 CALL=13\n"
"float32 dist\n"
"float32 theta_degree\n"
;
  }

  static const char* value(const ::robint_msgs::MotionCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.type);
      stream.next(m.dist);
      stream.next(m.theta_degree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::MotionCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::MotionCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
    s << indent << "theta_degree: ";
    Printer<float>::stream(s, indent + "  ", v.theta_degree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_MOTIONCOMMANDREQUEST_H
