// Generated by gencpp from file robint_msgs/OpenGateCommandRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_OPENGATECOMMANDREQUEST_H
#define ROBINT_MSGS_MESSAGE_OPENGATECOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct OpenGateCommandRequest_
{
  typedef OpenGateCommandRequest_<ContainerAllocator> Type;

  OpenGateCommandRequest_()
    : command(0)
    , gate_id()  {
    }
  OpenGateCommandRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , gate_id(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gate_id_type;
  _gate_id_type gate_id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(CONTINUE)
  #undef CONTINUE
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif

  enum {
    START = 0u,
    PAUSE = 1u,
    CONTINUE = 2u,
    STOP = 3u,
  };


  typedef boost::shared_ptr< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OpenGateCommandRequest_

typedef ::robint_msgs::OpenGateCommandRequest_<std::allocator<void> > OpenGateCommandRequest;

typedef boost::shared_ptr< ::robint_msgs::OpenGateCommandRequest > OpenGateCommandRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::OpenGateCommandRequest const> OpenGateCommandRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.gate_id == rhs.gate_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c4326d279ebe7dc6502ebaed684947d";
  }

  static const char* value(const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c4326d279ebe7dcULL;
  static const uint64_t static_value2 = 0x6502ebaed684947dULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/OpenGateCommandRequest";
  }

  static const char* value(const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 command       # 'Start', 'Pause', 'Continue', 'Stop'\n"
"uint8 START=0\n"
"uint8 PAUSE=1\n"
"uint8 CONTINUE=2\n"
"uint8 STOP=3\n"
"string gate_id\n"
;
  }

  static const char* value(const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.gate_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenGateCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::OpenGateCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "gate_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gate_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_OPENGATECOMMANDREQUEST_H
