// Generated by gencpp from file robint_msgs/ReviseVirtualWall.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_REVISEVIRTUALWALL_H
#define ROBINT_MSGS_MESSAGE_REVISEVIRTUALWALL_H

#include <ros/service_traits.h>


#include <robint_msgs/ReviseVirtualWallRequest.h>
#include <robint_msgs/ReviseVirtualWallResponse.h>


namespace robint_msgs
{

struct ReviseVirtualWall
{

typedef ReviseVirtualWallRequest Request;
typedef ReviseVirtualWallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReviseVirtualWall
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::ReviseVirtualWall > {
  static const char* value()
  {
    return "627f869a116b5a2b19b826607f45fdb8";
  }

  static const char* value(const ::robint_msgs::ReviseVirtualWall&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::ReviseVirtualWall > {
  static const char* value()
  {
    return "robint_msgs/ReviseVirtualWall";
  }

  static const char* value(const ::robint_msgs::ReviseVirtualWall&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::ReviseVirtualWallRequest> should match
// service_traits::MD5Sum< ::robint_msgs::ReviseVirtualWall >
template<>
struct MD5Sum< ::robint_msgs::ReviseVirtualWallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::ReviseVirtualWall >::value();
  }
  static const char* value(const ::robint_msgs::ReviseVirtualWallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::ReviseVirtualWallRequest> should match
// service_traits::DataType< ::robint_msgs::ReviseVirtualWall >
template<>
struct DataType< ::robint_msgs::ReviseVirtualWallRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::ReviseVirtualWall >::value();
  }
  static const char* value(const ::robint_msgs::ReviseVirtualWallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::ReviseVirtualWallResponse> should match
// service_traits::MD5Sum< ::robint_msgs::ReviseVirtualWall >
template<>
struct MD5Sum< ::robint_msgs::ReviseVirtualWallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::ReviseVirtualWall >::value();
  }
  static const char* value(const ::robint_msgs::ReviseVirtualWallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::ReviseVirtualWallResponse> should match
// service_traits::DataType< ::robint_msgs::ReviseVirtualWall >
template<>
struct DataType< ::robint_msgs::ReviseVirtualWallResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::ReviseVirtualWall >::value();
  }
  static const char* value(const ::robint_msgs::ReviseVirtualWallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_REVISEVIRTUALWALL_H
