// Generated by gencpp from file robint_msgs/SetChassisLight.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_SETCHASSISLIGHT_H
#define ROBINT_MSGS_MESSAGE_SETCHASSISLIGHT_H

#include <ros/service_traits.h>


#include <robint_msgs/SetChassisLightRequest.h>
#include <robint_msgs/SetChassisLightResponse.h>


namespace robint_msgs
{

struct SetChassisLight
{

typedef SetChassisLightRequest Request;
typedef SetChassisLightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetChassisLight
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::SetChassisLight > {
  static const char* value()
  {
    return "c59ddd3dc5cf36023f798fddbf4f62a0";
  }

  static const char* value(const ::robint_msgs::SetChassisLight&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::SetChassisLight > {
  static const char* value()
  {
    return "robint_msgs/SetChassisLight";
  }

  static const char* value(const ::robint_msgs::SetChassisLight&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::SetChassisLightRequest> should match
// service_traits::MD5Sum< ::robint_msgs::SetChassisLight >
template<>
struct MD5Sum< ::robint_msgs::SetChassisLightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::SetChassisLight >::value();
  }
  static const char* value(const ::robint_msgs::SetChassisLightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::SetChassisLightRequest> should match
// service_traits::DataType< ::robint_msgs::SetChassisLight >
template<>
struct DataType< ::robint_msgs::SetChassisLightRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::SetChassisLight >::value();
  }
  static const char* value(const ::robint_msgs::SetChassisLightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::SetChassisLightResponse> should match
// service_traits::MD5Sum< ::robint_msgs::SetChassisLight >
template<>
struct MD5Sum< ::robint_msgs::SetChassisLightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::SetChassisLight >::value();
  }
  static const char* value(const ::robint_msgs::SetChassisLightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::SetChassisLightResponse> should match
// service_traits::DataType< ::robint_msgs::SetChassisLight >
template<>
struct DataType< ::robint_msgs::SetChassisLightResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::SetChassisLight >::value();
  }
  static const char* value(const ::robint_msgs::SetChassisLightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_SETCHASSISLIGHT_H
