// Generated by gencpp from file robint_msgs/SetLedParams.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_SETLEDPARAMS_H
#define ROBINT_MSGS_MESSAGE_SETLEDPARAMS_H

#include <ros/service_traits.h>


#include <robint_msgs/SetLedParamsRequest.h>
#include <robint_msgs/SetLedParamsResponse.h>


namespace robint_msgs
{

struct SetLedParams
{

typedef SetLedParamsRequest Request;
typedef SetLedParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLedParams
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::SetLedParams > {
  static const char* value()
  {
    return "8ee2fcdcc512eade49a305e79b9688d9";
  }

  static const char* value(const ::robint_msgs::SetLedParams&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::SetLedParams > {
  static const char* value()
  {
    return "robint_msgs/SetLedParams";
  }

  static const char* value(const ::robint_msgs::SetLedParams&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::SetLedParamsRequest> should match
// service_traits::MD5Sum< ::robint_msgs::SetLedParams >
template<>
struct MD5Sum< ::robint_msgs::SetLedParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::SetLedParams >::value();
  }
  static const char* value(const ::robint_msgs::SetLedParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::SetLedParamsRequest> should match
// service_traits::DataType< ::robint_msgs::SetLedParams >
template<>
struct DataType< ::robint_msgs::SetLedParamsRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::SetLedParams >::value();
  }
  static const char* value(const ::robint_msgs::SetLedParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::SetLedParamsResponse> should match
// service_traits::MD5Sum< ::robint_msgs::SetLedParams >
template<>
struct MD5Sum< ::robint_msgs::SetLedParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::SetLedParams >::value();
  }
  static const char* value(const ::robint_msgs::SetLedParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::SetLedParamsResponse> should match
// service_traits::DataType< ::robint_msgs::SetLedParams >
template<>
struct DataType< ::robint_msgs::SetLedParamsResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::SetLedParams >::value();
  }
  static const char* value(const ::robint_msgs::SetLedParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_SETLEDPARAMS_H
