// Generated by gencpp from file robint_msgs/SetMotorControlModeRequest.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_SETMOTORCONTROLMODEREQUEST_H
#define ROBINT_MSGS_MESSAGE_SETMOTORCONTROLMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robint_msgs
{
template <class ContainerAllocator>
struct SetMotorControlModeRequest_
{
  typedef SetMotorControlModeRequest_<ContainerAllocator> Type;

  SetMotorControlModeRequest_()
    : mode(0)  {
    }
  SetMotorControlModeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(PARK)
  #undef PARK
#endif
#if defined(_WIN32) && defined(MANUAL)
  #undef MANUAL
#endif
#if defined(_WIN32) && defined(AUTO)
  #undef AUTO
#endif

  enum {
    PARK = 0u,
    MANUAL = 1u,
    AUTO = 2u,
  };


  typedef boost::shared_ptr< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMotorControlModeRequest_

typedef ::robint_msgs::SetMotorControlModeRequest_<std::allocator<void> > SetMotorControlModeRequest;

typedef boost::shared_ptr< ::robint_msgs::SetMotorControlModeRequest > SetMotorControlModeRequestPtr;
typedef boost::shared_ptr< ::robint_msgs::SetMotorControlModeRequest const> SetMotorControlModeRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator1> & lhs, const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371a486b8778648c39a09293972b9f68";
  }

  static const char* value(const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371a486b8778648cULL;
  static const uint64_t static_value2 = 0x39a09293972b9f68ULL;
};

template<class ContainerAllocator>
struct DataType< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robint_msgs/SetMotorControlModeRequest";
  }

  static const char* value(const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"uint8 PARK=0\n"
"uint8 MANUAL=1\n"
"uint8 AUTO=2\n"
;
  }

  static const char* value(const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMotorControlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robint_msgs::SetMotorControlModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_SETMOTORCONTROLMODEREQUEST_H
