// Generated by gencpp from file robint_msgs/SetMotionParams.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_SETMOTIONPARAMS_H
#define ROBINT_MSGS_MESSAGE_SETMOTIONPARAMS_H

#include <ros/service_traits.h>


#include <robint_msgs/SetMotionParamsRequest.h>
#include <robint_msgs/SetMotionParamsResponse.h>


namespace robint_msgs
{

struct SetMotionParams
{

typedef SetMotionParamsRequest Request;
typedef SetMotionParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotionParams
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::SetMotionParams > {
  static const char* value()
  {
    return "b5cbbb1ea5ef99ec2d9f8ade1e48feb3";
  }

  static const char* value(const ::robint_msgs::SetMotionParams&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::SetMotionParams > {
  static const char* value()
  {
    return "robint_msgs/SetMotionParams";
  }

  static const char* value(const ::robint_msgs::SetMotionParams&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::SetMotionParamsRequest> should match
// service_traits::MD5Sum< ::robint_msgs::SetMotionParams >
template<>
struct MD5Sum< ::robint_msgs::SetMotionParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::SetMotionParams >::value();
  }
  static const char* value(const ::robint_msgs::SetMotionParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::SetMotionParamsRequest> should match
// service_traits::DataType< ::robint_msgs::SetMotionParams >
template<>
struct DataType< ::robint_msgs::SetMotionParamsRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::SetMotionParams >::value();
  }
  static const char* value(const ::robint_msgs::SetMotionParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::SetMotionParamsResponse> should match
// service_traits::MD5Sum< ::robint_msgs::SetMotionParams >
template<>
struct MD5Sum< ::robint_msgs::SetMotionParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::SetMotionParams >::value();
  }
  static const char* value(const ::robint_msgs::SetMotionParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::SetMotionParamsResponse> should match
// service_traits::DataType< ::robint_msgs::SetMotionParams >
template<>
struct DataType< ::robint_msgs::SetMotionParamsResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::SetMotionParams >::value();
  }
  static const char* value(const ::robint_msgs::SetMotionParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_SETMOTIONPARAMS_H
