// Generated by gencpp from file robint_msgs/UpdateNavGoal.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_UPDATENAVGOAL_H
#define ROBINT_MSGS_MESSAGE_UPDATENAVGOAL_H

#include <ros/service_traits.h>


#include <robint_msgs/UpdateNavGoalRequest.h>
#include <robint_msgs/UpdateNavGoalResponse.h>


namespace robint_msgs
{

struct UpdateNavGoal
{

typedef UpdateNavGoalRequest Request;
typedef UpdateNavGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateNavGoal
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::UpdateNavGoal > {
  static const char* value()
  {
    return "548e99f135dd6026231a1f7b41de0e99";
  }

  static const char* value(const ::robint_msgs::UpdateNavGoal&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::UpdateNavGoal > {
  static const char* value()
  {
    return "robint_msgs/UpdateNavGoal";
  }

  static const char* value(const ::robint_msgs::UpdateNavGoal&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::UpdateNavGoalRequest> should match
// service_traits::MD5Sum< ::robint_msgs::UpdateNavGoal >
template<>
struct MD5Sum< ::robint_msgs::UpdateNavGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::UpdateNavGoal >::value();
  }
  static const char* value(const ::robint_msgs::UpdateNavGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::UpdateNavGoalRequest> should match
// service_traits::DataType< ::robint_msgs::UpdateNavGoal >
template<>
struct DataType< ::robint_msgs::UpdateNavGoalRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::UpdateNavGoal >::value();
  }
  static const char* value(const ::robint_msgs::UpdateNavGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::UpdateNavGoalResponse> should match
// service_traits::MD5Sum< ::robint_msgs::UpdateNavGoal >
template<>
struct MD5Sum< ::robint_msgs::UpdateNavGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::UpdateNavGoal >::value();
  }
  static const char* value(const ::robint_msgs::UpdateNavGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::UpdateNavGoalResponse> should match
// service_traits::DataType< ::robint_msgs::UpdateNavGoal >
template<>
struct DataType< ::robint_msgs::UpdateNavGoalResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::UpdateNavGoal >::value();
  }
  static const char* value(const ::robint_msgs::UpdateNavGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_UPDATENAVGOAL_H
