// Generated by gencpp from file robint_msgs/UpdateMap.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_UPDATEMAP_H
#define ROBINT_MSGS_MESSAGE_UPDATEMAP_H

#include <ros/service_traits.h>


#include <robint_msgs/UpdateMapRequest.h>
#include <robint_msgs/UpdateMapResponse.h>


namespace robint_msgs
{

struct UpdateMap
{

typedef UpdateMapRequest Request;
typedef UpdateMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateMap
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::UpdateMap > {
  static const char* value()
  {
    return "49d9b66697645b860ecd5f2cb94a4fc4";
  }

  static const char* value(const ::robint_msgs::UpdateMap&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::UpdateMap > {
  static const char* value()
  {
    return "robint_msgs/UpdateMap";
  }

  static const char* value(const ::robint_msgs::UpdateMap&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::UpdateMapRequest> should match
// service_traits::MD5Sum< ::robint_msgs::UpdateMap >
template<>
struct MD5Sum< ::robint_msgs::UpdateMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::UpdateMapRequest> should match
// service_traits::DataType< ::robint_msgs::UpdateMap >
template<>
struct DataType< ::robint_msgs::UpdateMapRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::UpdateMapResponse> should match
// service_traits::MD5Sum< ::robint_msgs::UpdateMap >
template<>
struct MD5Sum< ::robint_msgs::UpdateMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::UpdateMapResponse> should match
// service_traits::DataType< ::robint_msgs::UpdateMap >
template<>
struct DataType< ::robint_msgs::UpdateMapResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_UPDATEMAP_H
