// Generated by gencpp from file robint_msgs/UpdateMapList.msg
// DO NOT EDIT!


#ifndef ROBINT_MSGS_MESSAGE_UPDATEMAPLIST_H
#define ROBINT_MSGS_MESSAGE_UPDATEMAPLIST_H

#include <ros/service_traits.h>


#include <robint_msgs/UpdateMapListRequest.h>
#include <robint_msgs/UpdateMapListResponse.h>


namespace robint_msgs
{

struct UpdateMapList
{

typedef UpdateMapListRequest Request;
typedef UpdateMapListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateMapList
} // namespace robint_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robint_msgs::UpdateMapList > {
  static const char* value()
  {
    return "5b682de0bd32eef9ed86c7dc25bda0e8";
  }

  static const char* value(const ::robint_msgs::UpdateMapList&) { return value(); }
};

template<>
struct DataType< ::robint_msgs::UpdateMapList > {
  static const char* value()
  {
    return "robint_msgs/UpdateMapList";
  }

  static const char* value(const ::robint_msgs::UpdateMapList&) { return value(); }
};


// service_traits::MD5Sum< ::robint_msgs::UpdateMapListRequest> should match
// service_traits::MD5Sum< ::robint_msgs::UpdateMapList >
template<>
struct MD5Sum< ::robint_msgs::UpdateMapListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::UpdateMapList >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::UpdateMapListRequest> should match
// service_traits::DataType< ::robint_msgs::UpdateMapList >
template<>
struct DataType< ::robint_msgs::UpdateMapListRequest>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::UpdateMapList >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robint_msgs::UpdateMapListResponse> should match
// service_traits::MD5Sum< ::robint_msgs::UpdateMapList >
template<>
struct MD5Sum< ::robint_msgs::UpdateMapListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robint_msgs::UpdateMapList >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robint_msgs::UpdateMapListResponse> should match
// service_traits::DataType< ::robint_msgs::UpdateMapList >
template<>
struct DataType< ::robint_msgs::UpdateMapListResponse>
{
  static const char* value()
  {
    return DataType< ::robint_msgs::UpdateMapList >::value();
  }
  static const char* value(const ::robint_msgs::UpdateMapListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBINT_MSGS_MESSAGE_UPDATEMAPLIST_H
