(cl:in-package robint_msgs-msg)
(cl:export '(TARGET_POSE-VAL
          TARGET_POSE
          GOAL_TYPE-VAL
          GOAL_TYPE
          ENABLE_GOAL_CANDIDATE_SEARCH-VAL
          ENABLE_GOAL_CANDIDATE_SEARCH
          ENABLE_GOAL_INCREASE_TOLERANCE-VAL
          ENABLE_GOAL_INCREASE_TOLERANCE
          ENABLE_FIXED_STRAIGHT_PATH-VAL
          ENABLE_FIXED_STRAIGHT_PATH
))