(cl:in-package robint_msgs-srv)
(cl:export '(CHASSIS_HARDWARE_VERSION-VAL
          CHASSIS_HARDWARE_VERSION
          DRIVER_HARDWARE_VERSION-VAL
          DRIVER_HARDWARE_VERSION
          CHASSIS_SOFTWARE_VERSION-VAL
          CHASSIS_SOFTWARE_VERSION
          DRIVER_SOFTWARE_VERSION-VAL
          DRIVER_SOFTWARE_VERSION
          SUCCESS-VAL
          SUCCESS
          ERROR_CODE-VAL
          ERROR_CODE
))