PathWithPose[] paths
PathWithPoint boundary
uint8 mode
uint8 BackAndForth=0
uint8 Loop=1
int32 loop_count
float64 track_back_dist
bool enable_path_interpolation
string path_group_uuid
string coverage_method
bool enable_break_point
geometry_msgs/PoseStamped break_robot_pose
string break_subtask
int32 break_loop_index
---
---
geometry_msgs/PoseStamped base_position
int32 current_loop_index
float32 progress
bool high_speed_status
string subtask # "None", "Follow_Wall", "Track_OuterPath", "Track_InnerPath"
string state
uint8 status