# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robint_msgs/TrackingPathState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import robint_msgs.msg

class TrackingPathState(genpy.Message):
  _md5sum = "e85e55ca5dc1fe8c31d4a12fbf57df8e"
  _type = "robint_msgs/TrackingPathState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """TaskStateHeader header 
string path_name
string path_uuid
string path_group_uuid
string state
string feedback
uint8 r_state
uint8 r_feedback
float32 progress
int32 current_loop_index
string subtask
bool high_speed_status
bool finished
================================================================================
MSG: robint_msgs/TaskStateHeader
bool activate  # 该任务是否处于激活状态
time start_time
time stop_time
"""
  __slots__ = ['header','path_name','path_uuid','path_group_uuid','state','feedback','r_state','r_feedback','progress','current_loop_index','subtask','high_speed_status','finished']
  _slot_types = ['robint_msgs/TaskStateHeader','string','string','string','string','string','uint8','uint8','float32','int32','string','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,path_name,path_uuid,path_group_uuid,state,feedback,r_state,r_feedback,progress,current_loop_index,subtask,high_speed_status,finished

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrackingPathState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = robint_msgs.msg.TaskStateHeader()
      if self.path_name is None:
        self.path_name = ''
      if self.path_uuid is None:
        self.path_uuid = ''
      if self.path_group_uuid is None:
        self.path_group_uuid = ''
      if self.state is None:
        self.state = ''
      if self.feedback is None:
        self.feedback = ''
      if self.r_state is None:
        self.r_state = 0
      if self.r_feedback is None:
        self.r_feedback = 0
      if self.progress is None:
        self.progress = 0.
      if self.current_loop_index is None:
        self.current_loop_index = 0
      if self.subtask is None:
        self.subtask = ''
      if self.high_speed_status is None:
        self.high_speed_status = False
      if self.finished is None:
        self.finished = False
    else:
      self.header = robint_msgs.msg.TaskStateHeader()
      self.path_name = ''
      self.path_uuid = ''
      self.path_group_uuid = ''
      self.state = ''
      self.feedback = ''
      self.r_state = 0
      self.r_feedback = 0
      self.progress = 0.
      self.current_loop_index = 0
      self.subtask = ''
      self.high_speed_status = False
      self.finished = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4I().pack(_x.header.activate, _x.header.start_time.secs, _x.header.start_time.nsecs, _x.header.stop_time.secs, _x.header.stop_time.nsecs))
      _x = self.path_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.path_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.path_group_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.feedback
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Bfi().pack(_x.r_state, _x.r_feedback, _x.progress, _x.current_loop_index))
      _x = self.subtask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.high_speed_status, _x.finished))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = robint_msgs.msg.TaskStateHeader()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.header.activate, _x.header.start_time.secs, _x.header.start_time.nsecs, _x.header.stop_time.secs, _x.header.stop_time.nsecs,) = _get_struct_B4I().unpack(str[start:end])
      self.header.activate = bool(self.header.activate)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.path_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.path_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.path_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.path_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.path_group_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.path_group_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedback = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedback = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.r_state, _x.r_feedback, _x.progress, _x.current_loop_index,) = _get_struct_2Bfi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.subtask = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.subtask = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.high_speed_status, _x.finished,) = _get_struct_2B().unpack(str[start:end])
      self.high_speed_status = bool(self.high_speed_status)
      self.finished = bool(self.finished)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4I().pack(_x.header.activate, _x.header.start_time.secs, _x.header.start_time.nsecs, _x.header.stop_time.secs, _x.header.stop_time.nsecs))
      _x = self.path_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.path_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.path_group_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.feedback
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Bfi().pack(_x.r_state, _x.r_feedback, _x.progress, _x.current_loop_index))
      _x = self.subtask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.high_speed_status, _x.finished))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = robint_msgs.msg.TaskStateHeader()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.header.activate, _x.header.start_time.secs, _x.header.start_time.nsecs, _x.header.stop_time.secs, _x.header.stop_time.nsecs,) = _get_struct_B4I().unpack(str[start:end])
      self.header.activate = bool(self.header.activate)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.path_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.path_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.path_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.path_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.path_group_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.path_group_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedback = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedback = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.r_state, _x.r_feedback, _x.progress, _x.current_loop_index,) = _get_struct_2Bfi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.subtask = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.subtask = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.high_speed_status, _x.finished,) = _get_struct_2B().unpack(str[start:end])
      self.high_speed_status = bool(self.high_speed_status)
      self.finished = bool(self.finished)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_2Bfi = None
def _get_struct_2Bfi():
    global _struct_2Bfi
    if _struct_2Bfi is None:
        _struct_2Bfi = struct.Struct("<2Bfi")
    return _struct_2Bfi
_struct_B4I = None
def _get_struct_B4I():
    global _struct_B4I
    if _struct_B4I is None:
        _struct_B4I = struct.Struct("<B4I")
    return _struct_B4I
